### ISSUE TITLE
Use named delegates for `Observe` function

### ISSUE THREAD

**Issue by JakeGinnivan** [esp/esp-net#13]
That way r# can inspect the property names.

So instead of:
```
IDisposable Observe(Action<TModel, TEvent> onNext);
IDisposable Observe(Action<TModel, TEvent, TContext> onNext);
```

Have
```
public delegate void ObserverDelegate<TModel, TEvent>(TModel model, TEvent e);
public delegate void ObserverDelegate<TModel, TEvent, TContext>(TModel model, TEvent e, TContext context);

IDisposable Observe(ObserverDelegate<TModel, TEvent> onNext);
IDisposable Observe(ObserverDelegate<TModel, TEvent, TContext> onNext);
```
Name probably can be better but when you use r# smart completion you will get `(model, e, context) => ` rather than `(modelType, @event, arg3) => `

**Comment by KeithWoods** [comment]
Makes sense. We should do this for sure.

**Comment by KeithWoods** [comment]
Actually after looking at the change I don't see what' the benefit:

Current approach with Action : 
![withaction](https://cloud.githubusercontent.com/assets/2853674/8507519/b1aabed4-223e-11e5-945d-32d588e02490.jpg)

With Observerdelegate : 

![withobserverdelegate](https://cloud.githubusercontent.com/assets/2853674/8507521/c804902e-223e-11e5-9b80-83fc50fe6913.jpg)

What am I missing?

**Comment by KeithWoods** [comment]
pushed here if u want to check it out https://github.com/esp/esp-net/tree/issue/13

**Comment by KeithWoods** [comment]
BTW that branch name killed the build: `0.2.7-issue/13-0001' is not a valid version string`

**Comment by JakeGinnivan** [comment]
boom, nice bug :P

**Comment by JakeGinnivan** [comment]
# New api
![image](https://cloud.githubusercontent.com/assets/453152/8507562/7e4fbf0c-227b-11e5-8252-0cb15414b60b.png)

![image](https://cloud.githubusercontent.com/assets/453152/8507566/9202e664-227b-11e5-99ca-c355f86bc66f.png)

# Old API
![image](https://cloud.githubusercontent.com/assets/453152/8507571/bcee9be8-227b-11e5-8b4a-11e02e108c5d.png)

![image](https://cloud.githubusercontent.com/assets/453152/8507572/c4faf9b2-227b-11e5-8c2d-cdd18d3ca62a.png)


The first variable in the old api is guessed from the type name `TestModel` if it was `Foo` then the first variable would be `foo`. The new api in your branch will always pick the variable names from the named delegate

**Comment by JakeGinnivan** [comment]
It's small, but makes a difference when you write code via r# :P

**Comment by KeithWoods** [comment]
Ah i get it, you're talking about the generated method using smart completion:

R# generated with old API :
![image](https://cloud.githubusercontent.com/assets/2853674/8508171/bf5f154c-225d-11e5-9b13-b61907f3dc51.png)

R# generated with new API :

![image](https://cloud.githubusercontent.com/assets/2853674/8508176/e3a9c370-225d-11e5-81cb-e83e2735e34d.png)

I've to rename the delegate to `ObserveAction`. 

PR https://github.com/esp/esp-net/pull/21
