### ISSUE TITLE
Expose KnownEventTypes list from Router

### ISSUE THREAD

**Issue by JakeGinnivan** [esp/esp-net#14]
It would be handy to be able to get a list of events which have had observers created for, then a test could be written that all events in an assembly have handlers registered with the router.

**Comment by KeithWoods** [comment]
Not a massive fan of modifying the API for testing, I'd not want to encourage missuse for non test usage. However perhaps we could add some `TestHelper` or similar that can be queried in such instances. Another approach might implement the functionality via an explicit interface. `IRouterConfiguration`, or `IRouterTestHelper` or `IEventRegistrationMetaData`. humm

**Comment by JakeGinnivan** [comment]
Not sure how you could misuse, it would be exposing a ReadOnlyCollection of Types. If there is more than just that we end up wanting to expose then expose a .RegistrationMetaData property which is a readonly view of registration metdata.

**Comment by KeithWoods** [comment]
I've seen people try to infer logic based on events that flow through the system however this is different as you can't really do much with the list of all registered events. 

How about we expose an `ObservedEvents` property on the router of type `ObservedEventsMetaData`. It'd give you all the event types and number of observers. This way it stays off `IRouter<TModel>` but can easily be accessed for testing.

**Comment by KeithWoods** [comment]
I'm going to pick this up as part of #24 as implementing this will make the test code simpler.
