### ISSUE TITLE
Esp.Net.dll not getting version stamped at build time

### ISSUE THREAD

**Issue by KeithWoods** [esp/esp-net#39]
Version missing. This might be a regression: 

![image](https://cloud.githubusercontent.com/assets/2853674/9429764/424c8d16-49d4-11e5-922e-13443ae5a3b0.png)

**Comment by KeithWoods** [comment]
I think this 'should' be fixed as I renamed `AssemblyInfoCommon.cs` to `AssemblyInfo.Common.cs`, it appears that's what git version [looks for](https://github.com/GitTools/GitVersion/blob/master/src/GitVersionExe/AssemblyInfoFileUpdate.cs#L60). However nuget is blowing up using the `GitVersion_NuGetVersion` var created by gitversion.exe. 

Parking for now.

**Comment by rdingwall** [comment]
This is now fixed
