### ISSUE TITLE
EventObservable.Merge()

### ISSUE THREAD

**Issue by rdingwall** [esp/esp-net#40]
1. `EventObservable.Concat()` should be renamed to `Merge()` -- I think the naming is wrong, it doesn't look like it waits for stream 1 to complete before subscribing to stream2 as is the case with Rx Concat vs Merge.
2. `EventObservable.Concat()` should have a non-`params` overload i.e. `IEnumerable<IEventObservable<TModel, TEvent, TContext>> sources`

https://github.com/esp/esp-net/blob/master/src/Esp.Net/Reactive/EventObservable.cs#L46

**Comment by KeithWoods** [comment]
1 Good point, agree.
2 No probs
