### ISSUE TITLE
Can we optimise common Esp.Net usage to a single using statement?

### ISSUE THREAD

**Issue by rdingwall** [esp/esp-net#41]
From a library consumer point of view, it's nice if you can have the most common use cases encapsulated in a single namespace so you don't get too many `using` statements.

Model registration would be a good candidate for a sub-namespace (you probably only do it in one place), but Model-specific routers are not good for a sub-namespace because you use them everywhere in conjunction with types from the root namespace which means 2 `using` statements everywhere.

Could we possibly move all the interfaces in `Esp.Net.ModelRouter` up to the `Esp.Net` root namespace?

Concrete implementations can stay down in their sub namespaces.

**Comment by KeithWoods** [comment]
Yes we should push for this and I can do a sweep and lift as much as possible where it makes sense.

Regarding the `Esp.net.ModelRouter`, I went back and forth on that one and really disliked sticking it into it's own NS. The reason being was all types in there can exist at a higher level without conflict (as they are differentiated by their type parameter) except 1.

i.e: 
```

namespace Esp.Net
{
    public interface IModelSubject
    {
        IModelObservable<TModel> GetModelObservable<TModel>(object modelId);
    }
}

namespace Esp.Net.ModelRouter
{
    // can be lifted
    public interface IModelSubject<out TModel>
    {
        IModelObservable<TModel> GetModelObservable();
    }
}
```

However these 2 clash, hence the sub namespace for the lot:

```
namespace Esp.Net
{
    public interface IEventPublisher
    {
        void PublishEvent<TEvent>(object modelId, TEvent @event);
        void PublishEvent(object modelId, object @event);

        void ExecuteEvent<TEvent>(object modelId, TEvent @event);
        void ExecuteEvent(object modelId, object @event);

        void BroadcastEvent<TEvent>(TEvent @event);
        void BroadcastEvent(object @event);
    }
}

namespace Esp.Net.ModelRouter
{
    // can be lifted, has no type param
    public interface IEventPublisher
    {
        void PublishEvent<TEvent>(TEvent @event);
        void PublishEvent(object @event);

        void ExecuteEvent<TEvent>(TEvent @event);
        void ExecuteEvent(object @event);

        void BroadcastEvent<TEvent>(TEvent @event);
        void BroadcastEvent(object @event);
    }
}
```

IEventPublisher could have different name for the model specific variant or perhaps could be merged into one of the other interfaces. Will have to give it some thought.

**Comment by rdingwall** [comment]
Maybe to make it clear, all model-specific interfaces should have a `TModel` type parameter? (even if not technically required as above)
