### ISSUE TITLE
Esp.Net on symbolsource.org

### ISSUE THREAD

**Issue by rdingwall** [esp/esp-net#42]
It would be good if we could modify the CI build script to also produce a `.symbol.nupkg` which NuGet Push will automatically upload to symbolsource.org.

Here is an example appveyor script that does it:

https://github.com/rdingwall/protobuf-net-data/blob/master/appveyor.yml

And the docs:

https://docs.nuget.org/create/creating-and-publishing-a-symbol-package

**Comment by KeithWoods** [comment]
Good idea
