### ISSUE TITLE
Make Router(threadGuard) constructor parameter optional

### ISSUE THREAD

**Issue by rdingwall** [esp/esp-net#43]
The default `Router` constructor for most users should simply use `ThreadGuard.Default`. An overload will allow users to pass their own thread guard.

**Comment by KeithWoods** [comment]
Yep makes sense. I think initially I was thinking of forcing users to consider the threading aspect, however it's not really required. Diligent users will be wondering about it and documentation should cover the threading model.

**Comment by raybooysen** [comment]
Pit of success, pit of success, pit of success!

**Comment by raybooysen** [comment]
In Rx.net, all the operators that introduce concurrency have optional Schedulers.  The best thing about RxJava is that they removed all the overloads that didn't take a scheduler to FORCE the user to think about it.

**Comment by KeithWoods** [comment]
On second thoughts most users shouldn't be using `ThreadGuard.Default`. That should be renamed to `ThreadGuard.CurrentThread`. 

I think Ray makes some good points here. If you ignore that then you're going to end up with race conditions and a broken model.

**Comment by rdingwall** [comment]
Makes sense to me - it's a real choice now not just a mandatory default.

Looking at the source for ThreadGuard however it looks like `ThreadGuard.Default` allows events to be published from any thread and therefore should really be renamed `ThreadGuard.Unsafe` or something?

**Comment by KeithWoods** [comment]
Yeah `.Unsafe` is a good naming idea.

**Comment by raybooysen** [comment]
The downside of what happens now is that the only implementation suggests the setup (by default) is unsafe.  We need a "safe" impl

**Comment by KeithWoods** [comment]
This isn't really by default. The default is you need to implement an interface to guard against incorrect access via another thread and provide it when creating a router: `new Router(yourThreadGuard);`. `ThreadGuard.Unsafe` is an out of the box implementation that doesn't do any checking. 

You could have `ThreadGuard.CurrentThread` (then perhaps do equality comparison on thread instance or thread id to figure this out when required?). A a parametersless  ctor could use that by default. 

Thoughts?

**Comment by rdingwall** [comment]
Maybe renaming to `ICheckAccess` would be more understandable for most .NET developers?

What are the likely threading scenarios we need to support?

* Single threaded processes, including Simple WPF/Winforms/Silverlight apps running router running on UI thread could use the existing implementation which could be called `CheckAccess.None`
* Router running on a special thread started by the user. Could use something like `CheckAccess.ThreadId(int)` or a shortcut `CheckAccess.CurrentThread`?
* Any other situations?

**Comment by rdingwall** [comment]
Actually do we need more support to make a threadsafe `IRouter` so users don't need to write their own dispatchers to ensure all events are published on the same thread?

**Comment by rdingwall** [comment]
I think the whole threading story needs a bit more support for users. At the moment I'm trying to:

1. Ensure all events are dispatched on the router thread (need to wrap all access to `IRouter` / `IRouter<T>`)
2. Ensure all event subscriptions are observed on the router thread (difficult because there is no `ObserveOn()` extension method)

I'm needing to write wrappers for everything at the moment.

**Comment by KeithWoods** [comment]
For point 1 we could introduce a dispatcher (similar to an rx scheduler but no notion of time)  to the mix, then replace `IThreadGuard` with that. It's job would be to always dispatch execution on that dispatchers thread. It could do a simple check and reschedule work if it come's in on the wrong thread. 

``` c#
public interface  IRouterDispatcher 
{
   bool CheckAccess();
   void Schedule(Action action)
}
```

We could provide a UI implementation of this in a seperate GUI package and a 'new thread' implementation in the core package.

Note there is some complications with this approach. It will work well for fire and forget operations like publishing an event. However for `Router.GetEventObservable()` there are internal state updates when that method is called, then again when the observable is subscribed to. There will need to be some thought there.

Thoughts?

For point 2 that should never be a problem as it's the `Routers` job to dispatch events, it will always do this on the right thread (currently using IThreadGuard). Any extensions to the reactive components (i.e. .Take(), .Select() etc)  don't support scheduling (which is a key design decision to maintain the event workflow deterministic processing model).

**Comment by rdingwall** [comment]
That interface looks perfect @KeithWoods. `Router.GetEventObservable()` is already protected by the thread guard so that should be covered. (Maybe the router will need to check access again when observable is subscribed to).

**Comment by KeithWoods** [comment]
I've started putting in multi threading support for 0.2.15 release:
https://github.com/esp/esp-net/tree/0.2.15

Another set of eyes would be good if anyone has time.
