### ISSUE TITLE
Observing base event without knowing all the sub events up front

### ISSUE THREAD

**Issue by rdingwall** [esp/esp-net#45]
The interface that allows you to subscribe for base event types doesn't provide much value because you are required to provide the sub event type as well. The `GetEventObservable<TBaseEvent>(Type subEventType)` is really just registering for a sub type and casting it back to the base type.

It is not possible for example to observe all sub types of a given base event. This test fails:

```csharp
[TestFixture]
public class TestFixture
{
    [Test]
    public void Name()
    {
        var router = new Router(ThreadGuard.Default);
        var modelId = Guid.NewGuid();
        router.RegisterModel(modelId, new Model());
        router.GetEventObservable<Model, BaseEvent>(modelId).Observe((model, ev) => Assert.Pass());
        router.PublishEvent(modelId, new SubEvent());
        Assert.Fail();
    }

    public class SubEvent : BaseEvent {}
    public class BaseEvent {}
    public class Model {}
}
```

Similarly it isn't possible to subscribe for generic events:

```csharp
[TestFixture]
public class TestFixture2
{
    [Test]
    public void Name()
    {
        var router = new Router(ThreadGuard.Default);
        var modelId = Guid.NewGuid();
        router.RegisterModel(modelId, new Model());
        router.GetEventObservable<Model, BaseEvent>(modelId).Observe((model, ev) => Assert.Pass());
        router.PublishEvent(modelId, new SubEvent<string>());
        Assert.Fail();
    }

    public class SubEvent<T> : BaseEvent { }
    public class BaseEvent { }
    public class Model { }
}
```

Is this something we want to support? Potentially you could modify `ModelEntry._eventSubjects` from a `Dictionary<Type, dynamic>` to a custom `EventSubjectCollection` which allows lookup by base and open generic event type plus modifying `EventSubject` to support converting to a base type stream...

**Comment by KeithWoods** [comment]
I agree this overload makes things confusing. What's more there is another overload that just back onto this one, i.e. the first just back onto the second: 

``` c# 
IEventObservable<TModel, TBaseEvent, IEventContext> GetEventObservable<TModel, TSubEventType, TBaseEvent>(object modelId, ObservationStage observationStage = ObservationStage.Normal) where TSubEventType : TBaseEvent;
IEventObservable<TModel, TBaseEvent, IEventContext> GetEventObservable<TModel, TBaseEvent>(object modelId, Type subEventType, ObservationStage observationStage = ObservationStage.Normal);
  
```

in 0.2.15 I'm removing the first overload.

What the second overload above is really designed to do is allow you to subscribe to some base event type. Yes currently you need to know the derived type up front. At first glance this seems kinda useless however when combined with `EventObservable.Concat` (soon to be correctly renamed to Merge) it is actually of use. It allows you to have a single stream of many differing event types all sharing a common base. It effectively is a poor mans version of what you are suggesting.

You're proposed changes are much cleaner and it's something we should do pending a review of how to do it. I'll have a more details look into your suggestion.

**Comment by KeithWoods** [comment]
This is mostly done in 0.5.3. 

I've removed the confusing overload for `GetEventObservable`, there is only one now. And you can just pass a base event type to it. Similarly I updated the attribute based event observation so they all use the same attributes.

This now passes:
``` cs
[Test]
public void Issue45TestCase()
{
    var router = new Router<TestModel>(new TestModel());
    router.GetEventObservable<BaseEvent>().Observe((ev, model) => Assert.Pass());
    router.PublishEvent(new Event1());
    Assert.Fail();
}

```

I've not coded the observation of open generic events
